# Generated by Django 5.2.1 on 2025-05-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tmdb_id',
            field=models.PositiveIntegerField(),
        ),
    ]
