# Generated by Django 5.2.1 on 2025-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_alter_rating_options_alter_rating_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='rating',
            name='tmdb_id',
            field=models.IntegerField(),
        ),
    ]
