# Generated by Django 5.2.1 on 2025-05-21 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_alter_rating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
